### ISSUE TITLE
Temp file is empty and can't save(no permission)

### ISSUE THREAD

**Issue by yorkbai** [cdpath/alfred_workflows#1]
good job!  
I got the error info in debug window after installed it on alfred3.4.1 . plz!
 
![image](https://user-images.githubusercontent.com/7995150/29156326-d850cb08-7dd3-11e7-845d-3b84fdbe1133.png)

**Comment by cdpath** [comment]
@yorkbai Oh, you forget to set `tmpdir`.

run `echo $TMPDIR` and paste what you get here:

![](https://user-images.githubusercontent.com/11472839/31922394-4947d168-b8a7-11e7-9519-dcdc97153761.png)

**Comment by yorkbai** [comment]
/var/folders/7w/0p_5rvx13cx22hqtwhc1hz_m0000gn/T/    after run  'echo $TMPDIR'

**Comment by yorkbai** [comment]
thanks! I can edit it after setting $TMPDIR !   👍
another question: I using alfred's clipboard ,  we know there save much history record , can we modify them?

**Comment by cdpath** [comment]
@yorkbai Only the latest clipboard history item will be modified with this workflow. Surely you can use syntax like `{clipboard:10}` to modify the 10th one, which is not convenient at all (you have to got the ordinal number beforehand).

**Comment by yorkbai** [comment]
all item save in "clipboard.alfdb" file , I think we can get all of  them.
```
import sqlite3
import pickle
import re
import csv

def main():
    db_file  = "~/Library/Application Support/Alfred 3/Databases/clipboard.alfdb"
    try:
        conn = sqlite3.connect(db_file)
    except Error as e:
        print(e)
    with conn:
        sql = "select * from clipboard;"
        cur = conn.cursor()
        cur.execute(sql)
        result = cur.fetchall()
        if result:
            with open('output.csv', 'wb') as f:
                writer = csv.writer(f)
                writer.writerows(result)

if __name__ == '__main__':
    main()
```
