### ISSUE TITLE
table to markdown

### ISSUE THREAD

**Issue by huahuayu** [cdpath/alfred_workflows#2]
hi, I saw your introduction in https://www.alfredforum.com/topic/11199-convert-to-markdown-table/ and installed the workflow, but when I copied a table from a website and paste with command + control + t but nothing pasted, how to use it?
![image](https://user-images.githubusercontent.com/1725060/58383492-3d6b9600-800a-11e9-8c36-76c4eb05a845.png)

**Comment by cdpath** [comment]
Double click Hotkey (which is empty now) and assign it to <kbd>CMD-Ctrl-T</kbd>.

**Comment by huahuayu** [comment]
> Double click Hotkey (which is empty now) and assign it to CMD-Ctrl-T.

I just set the hotkey, and close the Alfred setting windows, press the key, nothing happens, or call Alfred by cmd + space then press the hotkey cmd + ctrl + t, nothing happened.

I found https://thisdavej.com/copy-table-in-excel-and-paste-as-a-markdown-table/ work for me

**Comment by cdpath** [comment]
Excel is not supported.
